# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "centos/7",
	:box_version => "1804.02",
        :ip_addr => '192.168.10.10'
  },
  :client => {
        :box_name => "centos/7",
	:box_version => "1804.02",
        :ip_addr => '192.168.10.11'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.box_version = boxconfig[:box_version]
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.host_name = boxname.to_s

   config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  
   end

end
end
end
