# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

  :ABR1 => {
    :box_name => "centos/7",
    :net => [
              {adapter: 2, auto_config: false, virtualbox__intnet: "vlan12"},
              {adapter: 3, auto_config: false, virtualbox__intnet: "vlan16"},
              {ip: '10.1.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "Area 1"},
            ]
  }, 

  :ABR2 => {
    :box_name => "centos/7",
    :net => [
              {adapter: 2, auto_config: false, virtualbox__intnet: "vlan12"},
              {adapter: 3, auto_config: false, virtualbox__intnet: "vlan20"},
              {ip: '10.2.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "Area 2"},
            ]
  }, 

  :ABR3 => {
    :box_name => "centos/7",
    :net => [
              {adapter: 2, auto_config: false, virtualbox__intnet: "vlan16"},
              {adapter: 3, auto_config: false, virtualbox__intnet: "vlan20"},
              {ip: '10.3.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "Area 3"},
            ]
  }, 

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
          timedatectl set-timezone Europe/Moscow
        SHELL
        
        case boxname.to_s

          when "ABR1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              setsebool -P zebra_write_config 1
              yum install quagga traceroute -y
              cp /vagrant/network-scripts/ifcfg-vlan12.ABR1 /etc/sysconfig/network-scripts/ifcfg-vlan12
              cp /vagrant/network-scripts/ifcfg-vlan16.ABR1 /etc/sysconfig/network-scripts/ifcfg-vlan16
              cp /vagrant/quagga/daemons /etc/quagga/daemons
              cp /vagrant/quagga/zebra.conf.ABR1 /etc/quagga/zebra.conf
              cp /vagrant/quagga/ospfd.conf.ABR1 /etc/quagga/ospfd.conf
              chown quagga. /etc/quagga/daemons
              chown quagga. /etc/quagga/ospfd.conf
              chown quagga. /etc/quagga/zebra.conf
              echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter = 0 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              systemctl enable zebra
              systemctl start zebra
              systemctl enable ospfd
              systemctl start ospfd
              SHELL
          when "ABR2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              setsebool -P zebra_write_config 1
              yum install quagga traceroute -y
              cp /vagrant/network-scripts/ifcfg-vlan12.ABR2 /etc/sysconfig/network-scripts/ifcfg-vlan12
              cp /vagrant/network-scripts/ifcfg-vlan20.ABR2 /etc/sysconfig/network-scripts/ifcfg-vlan20
              cp /vagrant/quagga/daemons /etc/quagga/daemons              
              cp /vagrant/quagga/zebra.conf.ABR2 /etc/quagga/zebra.conf
              cp /vagrant/quagga/ospfd.conf.ABR2 /etc/quagga/ospfd.conf
              chown quagga. /etc/quagga/daemons
              chown quagga. /etc/quagga/ospfd.conf
              chown quagga. /etc/quagga/zebra.conf
              echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter = 0 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              systemctl enable zebra
              systemctl start zebra
              systemctl enable ospfd
              systemctl start ospfd
              SHELL
          when "ABR3"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              setsebool -P zebra_write_config 1
              yum install quagga traceroute -y
              cp /vagrant/network-scripts/ifcfg-vlan16.ABR3 /etc/sysconfig/network-scripts/ifcfg-vlan16
              cp /vagrant/network-scripts/ifcfg-vlan20.ABR3 /etc/sysconfig/network-scripts/ifcfg-vlan20
	      cp /vagrant/quagga/daemons /etc/quagga/daemons
              cp /vagrant/quagga/zebra.conf.ABR3 /etc/quagga/zebra.conf
              cp /vagrant/quagga/ospfd.conf.ABR3 /etc/quagga/ospfd.conf
              chown quagga. /etc/quagga/daemons
              chown quagga. /etc/quagga/ospfd.conf
              chown quagga. /etc/quagga/zebra.conf
              echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter = 0 >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              systemctl restart network
              systemctl enable zebra
              systemctl start zebra
              systemctl enable ospfd
              systemctl start ospfd
              SHELL

        end

      end

  end
  
end
