# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.1', adapter: 2, netmask: "255.255.255.0"}
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
      
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
          timedatectl set-timezone Europe/Moscow
        SHELL
        
        case boxname.to_s
          when "server"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              setenforce 0
              echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
              sysctl -p /etc/sysctl.conf
              yum update -y
              yum install epel-release -y
              yum install openvpn wget -y
              mkdir /etc/openvpn/certs
              mkdir /etc/openvpn/keys
              cp /vagrant/server/ca.crt /etc/openvpn/certs
              cp /vagrant/server/server.crt /etc/openvpn/certs
              cp /vagrant/server/dh.pem /etc/openvpn/keys
              cp /vagrant/server/server.key /etc/openvpn/keys
              cp /vagrant/server/ta.key /etc/openvpn/keys
              cp /vagrant/server/server.conf /etc/openvpn/
              systemctl restart openvpn@server
              SHELL
          end
       end
   end
end
