# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "nginx"
  config.vm.network "private_network", ip: "192.168.1.15"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    yum install epel-release -y
    yum install nginx -y
    cp /vagrant/nginx.conf /etc/nginx
    systemctl enable nginx
    systemctl start nginx
  SHELL
end
